In [7]:
import numpy as np

print(np.eye(5,3,k=-1))
print(np.array([[1,2,3], [4,5,6]]))

[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
[[1 2 3]
 [4 5 6]]


In [46]:
import numpy as np

a = np.eye(3,4,0)*2
b = np.eye(3,4,1)
mat = a + b
mat = mat.flatten().reshape(12,1)
print(mat)

[[ 2.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 2.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 2.]
 [ 1.]]


In [31]:
import random

w = np.array(random.sample(range(1000), 12))
w = w.reshape(2,2,3)
print(w)
print(w.transpose(0,2,1))


[[[114 247 394]
  [337 660 795]]

 [[928 148 849]
  [465 617 784]]]
[[[114 337]
  [247 660]
  [394 795]]

 [[928 465]
  [148 617]
  [849 784]]]


In [53]:
v = np.array([[1,2,3,4], [1,2,3,4], [1,2,3,4]])
print(v)
print(v.mean(axis=0))
print(v.mean(axis=1))
print(v.mean(axis=None))

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[ 1.  2.  3.  4.]
[ 2.5  2.5  2.5]
2.5


In [31]:
import numpy as np

x_shape = tuple(map(int, input().split()))
X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)
y_shape = tuple(map(int, input().split()))
Y = np.fromiter(map(int, input().split()), np.int).reshape(y_shape)
Yt = np.transpose(Y)
if x_shape[1] != y_shape[1]:
    print('matrix shapes do not match')
else:
    Dotprod = np.dot(X,Yt)
    print(Dotprod)


2 3
5 9 9 10 8 9
3 4
6 11 3 5 4 5 3 2 5 8 2 2
matrix shapes do not match


In [1]:
from urllib.request import urlopen
import numpy as np

f = urlopen('https://stepic.org/media/attachments/lesson/16462/boston_houses.csv')
bost_houses = np.loadtxt(f, usecols=(range(7)), skiprows=1, delimiter=",")
print(bost_houses.mean(axis=0))

[ 22.53280632   3.61352356  11.36363636   0.06916996   0.55469506
   6.28463439   3.79504269]


In [23]:
import urllib
from urllib import request
import numpy as np


fname = 'https://stepic.org/media/attachments/lesson/16462/boston_houses.csv'  # read file name from stdin
f = urllib.request.urlopen(fname)  # open file from URL
data = np.loadtxt(f, delimiter=',', skiprows=1)  # load data to work with
Y = data[:,0]
X = data[:,range(1,7)]
X_ones = np.c_[np.ones_like(Y), X]
X_transp = np.transpose(X_ones)
XX_prod = np.dot(X_transp, X_ones)
XX_inv = np.linalg.inv(XX_prod)
Beta = np.dot(np.dot(XX_inv,X_transp),Y)
print(*Beta)










-3.65580428506 -0.216395502369 0.0737305981755 4.41245057691 -25.4684487841 7.14320155075 -1.30108767765


In [5]:
import numpy as np
a = np.array([1,2,3,5,6,14,2,4])
b = a + 1
c = (b > 3) * 1
#c = c*1
print (c)

[0 0 1 1 1 1 0 1]
